spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todaktodak?serverTimezone=Asia/Seoul
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true
          enable_lazy_load_no_trans: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher